# --- !Ups

create table "USER" (
  "USER_ID" bigint generated by default as identity(start with 1) not null primary key,
  "FIRST_NAME" varchar not null,
  "LAST_NAME" varchar not null,
  "EMAIL" varchar not null,
  "PASSWORD" varchar not null,
  "INFO" varchar
);

create table "POST" (
  "POST_ID" bigint generated by default as identity(start with 1) not null primary key,
  "USER_ID" bigint not null,
  "CONTENT" varchar not null,
  "LIKES_COUNT" int not null,
  "DISLIKES_COUNT" int not null,
  "DATE" date not null
);

# --- !Downs

drop table "USER" if exists;
drop table "POST" if exists;
